#define COMMA                           1
#define PLUS                            2
#define MINUS                           3
#define DIV                             4
#define TIMES                           5
#define NEWLINE                         6
#define DELIMETER                       7
#define ASSIGN                          8
#define SEMICOLON                       9
#define LPAREN                         10
#define RPAREN                         11
#define PIPE                           12
#define LESS                           13
#define LESS_EQUAL                     14
#define NOT_EQUAL                      15
#define EQUAL                          16
#define GREATER_EQUAL                  17
#define GREATER                        18
#define FORLOOP_BEGIN                  19
#define FORLOOP_END                    20
#define DOUBLE_VAL                     21
#define PARAM_NAME                     22
#define PROD_NAME                      23
#define COMMAND                        24
#define NEURON                         25
